/*
 * This file is generated by jOOQ.
 */
package com.example.demo.entites;


import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/** OAuth Client */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(
    name = "oauth2_client",
    uniqueConstraints = {
      @UniqueConstraint(
          name = "pk_oauth2_client",
          columnNames = {"id"}),
      @UniqueConstraint(
          name = "uk_oauth2_client",
          columnNames = {"client_id"})
    })
public class Oauth2ClientEntity implements Serializable {

  private static final long serialVersionUID = 1L;

  private String id;
  private String clientId;
  private LocalDateTime clientIdIssuedAt;
  private String clientSecret;
  private LocalDateTime clientSecretExpiresAt;
  private String clientName;
  private LocalDateTime createdDate;
  private String createdBy;
  private LocalDateTime lastModifiedDate;
  private String lastModifiedBy;

  public Oauth2ClientEntity() {}

  public Oauth2ClientEntity(Oauth2ClientEntity value) {
    this.id = value.id;
    this.clientId = value.clientId;
    this.clientIdIssuedAt = value.clientIdIssuedAt;
    this.clientSecret = value.clientSecret;
    this.clientSecretExpiresAt = value.clientSecretExpiresAt;
    this.clientName = value.clientName;
    this.createdDate = value.createdDate;
    this.createdBy = value.createdBy;
    this.lastModifiedDate = value.lastModifiedDate;
    this.lastModifiedBy = value.lastModifiedBy;
  }

  public Oauth2ClientEntity(
      String id,
      String clientId,
      LocalDateTime clientIdIssuedAt,
      String clientSecret,
      LocalDateTime clientSecretExpiresAt,
      String clientName,
      LocalDateTime createdDate,
      String createdBy,
      LocalDateTime lastModifiedDate,
      String lastModifiedBy) {
    this.id = id;
    this.clientId = clientId;
    this.clientIdIssuedAt = clientIdIssuedAt;
    this.clientSecret = clientSecret;
    this.clientSecretExpiresAt = clientSecretExpiresAt;
    this.clientName = clientName;
    this.createdDate = createdDate;
    this.createdBy = createdBy;
    this.lastModifiedDate = lastModifiedDate;
    this.lastModifiedBy = lastModifiedBy;
  }

  /** Getter for <code>public.oauth2_client.id</code>. */
  @Id
  @Column(name = "id", nullable = false, length = 10)
  @NotNull
  @Size(max = 10)
  public String getId() {
    return this.id;
  }

  /** Setter for <code>public.oauth2_client.id</code>. */
  public void setId(String id) {
    this.id = id;
  }

  /** Getter for <code>public.oauth2_client.client_id</code>. Client 帳號 */
  @Column(name = "client_id", nullable = false, length = 100)
  @NotNull
  @Size(max = 100)
  public String getClientId() {
    return this.clientId;
  }

  /** Setter for <code>public.oauth2_client.client_id</code>. Client 帳號 */
  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  /** Getter for <code>public.oauth2_client.client_id_issued_at</code>. 發佈時間 */
  @Column(name = "client_id_issued_at", nullable = false, precision = 6)
  public LocalDateTime getClientIdIssuedAt() {
    return this.clientIdIssuedAt;
  }

  /** Setter for <code>public.oauth2_client.client_id_issued_at</code>. 發佈時間 */
  public void setClientIdIssuedAt(LocalDateTime clientIdIssuedAt) {
    this.clientIdIssuedAt = clientIdIssuedAt;
  }

  /** Getter for <code>public.oauth2_client.client_secret</code>. 密碼 */
  @Column(name = "client_secret", length = 200)
  @Size(max = 200)
  public String getClientSecret() {
    return this.clientSecret;
  }

  /** Setter for <code>public.oauth2_client.client_secret</code>. 密碼 */
  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }

  /** Getter for <code>public.oauth2_client.client_secret_expires_at</code>. 過期時間 */
  @Column(name = "client_secret_expires_at", precision = 6)
  public LocalDateTime getClientSecretExpiresAt() {
    return this.clientSecretExpiresAt;
  }

  /** Setter for <code>public.oauth2_client.client_secret_expires_at</code>. 過期時間 */
  public void setClientSecretExpiresAt(LocalDateTime clientSecretExpiresAt) {
    this.clientSecretExpiresAt = clientSecretExpiresAt;
  }

  /** Getter for <code>public.oauth2_client.client_name</code>. 名稱 */
  @Column(name = "client_name", nullable = false, length = 200)
  @NotNull
  @Size(max = 200)
  public String getClientName() {
    return this.clientName;
  }

  /** Setter for <code>public.oauth2_client.client_name</code>. 名稱 */
  public void setClientName(String clientName) {
    this.clientName = clientName;
  }

  /** Getter for <code>public.oauth2_client.created_date</code>. */
  @Column(name = "created_date", nullable = false, precision = 6)
  @NotNull
  public LocalDateTime getCreatedDate() {
    return this.createdDate;
  }

  /** Setter for <code>public.oauth2_client.created_date</code>. */
  public void setCreatedDate(LocalDateTime createdDate) {
    this.createdDate = createdDate;
  }

  /** Getter for <code>public.oauth2_client.created_by</code>. */
  @Column(name = "created_by", nullable = false, length = 36)
  @NotNull
  @Size(max = 36)
  public String getCreatedBy() {
    return this.createdBy;
  }

  /** Setter for <code>public.oauth2_client.created_by</code>. */
  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  /** Getter for <code>public.oauth2_client.last_modified_date</code>. */
  @Column(name = "last_modified_date", precision = 6)
  public LocalDateTime getLastModifiedDate() {
    return this.lastModifiedDate;
  }

  /** Setter for <code>public.oauth2_client.last_modified_date</code>. */
  public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  /** Getter for <code>public.oauth2_client.last_modified_by</code>. */
  @Column(name = "last_modified_by", length = 36)
  @Size(max = 36)
  public String getLastModifiedBy() {
    return this.lastModifiedBy;
  }

  /** Setter for <code>public.oauth2_client.last_modified_by</code>. */
  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }
}
