/*
 * This file is generated by jOOQ.
 */
package com.example.demo.entites;


import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/** client 申請範圍 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(
    name = "oauth2_client_scope",
    uniqueConstraints = {
      @UniqueConstraint(
          name = "pk_oauth2_client_scope",
          columnNames = {"id"}),
      @UniqueConstraint(
          name = "uk_oauth2_client_scope",
          columnNames = {"oauth2_client_id", "resource_scope_id"})
    })
public class Oauth2ClientScopeEntity implements Serializable {

  private static final long serialVersionUID = 1L;

  private String id;
  private String oauth2ClientId;
  private String resourceScopeId;
  private LocalDateTime createdDate;
  private String createdBy;
  private LocalDateTime lastModifiedDate;
  private String lastModifiedBy;

  public Oauth2ClientScopeEntity() {}

  public Oauth2ClientScopeEntity(Oauth2ClientScopeEntity value) {
    this.id = value.id;
    this.oauth2ClientId = value.oauth2ClientId;
    this.resourceScopeId = value.resourceScopeId;
    this.createdDate = value.createdDate;
    this.createdBy = value.createdBy;
    this.lastModifiedDate = value.lastModifiedDate;
    this.lastModifiedBy = value.lastModifiedBy;
  }

  public Oauth2ClientScopeEntity(
      String id,
      String oauth2ClientId,
      String resourceScopeId,
      LocalDateTime createdDate,
      String createdBy,
      LocalDateTime lastModifiedDate,
      String lastModifiedBy) {
    this.id = id;
    this.oauth2ClientId = oauth2ClientId;
    this.resourceScopeId = resourceScopeId;
    this.createdDate = createdDate;
    this.createdBy = createdBy;
    this.lastModifiedDate = lastModifiedDate;
    this.lastModifiedBy = lastModifiedBy;
  }

  /** Getter for <code>public.oauth2_client_scope.id</code>. */
  @Id
  @Column(name = "id", nullable = false, length = 10)
  @NotNull
  @Size(max = 10)
  public String getId() {
    return this.id;
  }

  /** Setter for <code>public.oauth2_client_scope.id</code>. */
  public void setId(String id) {
    this.id = id;
  }

  /** Getter for <code>public.oauth2_client_scope.oauth2_client_id</code>. OAuth Client ID */
  @Column(name = "oauth2_client_id", nullable = false, length = 10)
  @NotNull
  @Size(max = 10)
  public String getOauth2ClientId() {
    return this.oauth2ClientId;
  }

  /** Setter for <code>public.oauth2_client_scope.oauth2_client_id</code>. OAuth Client ID */
  public void setOauth2ClientId(String oauth2ClientId) {
    this.oauth2ClientId = oauth2ClientId;
  }

  /** Getter for <code>public.oauth2_client_scope.resource_scope_id</code>. 權限ID */
  @Column(name = "resource_scope_id", nullable = false, length = 10)
  @NotNull
  @Size(max = 10)
  public String getResourceScopeId() {
    return this.resourceScopeId;
  }

  /** Setter for <code>public.oauth2_client_scope.resource_scope_id</code>. 權限ID */
  public void setResourceScopeId(String resourceScopeId) {
    this.resourceScopeId = resourceScopeId;
  }

  /** Getter for <code>public.oauth2_client_scope.created_date</code>. */
  @Column(name = "created_date", nullable = false, precision = 6)
  @NotNull
  public LocalDateTime getCreatedDate() {
    return this.createdDate;
  }

  /** Setter for <code>public.oauth2_client_scope.created_date</code>. */
  public void setCreatedDate(LocalDateTime createdDate) {
    this.createdDate = createdDate;
  }

  /** Getter for <code>public.oauth2_client_scope.created_by</code>. */
  @Column(name = "created_by", nullable = false, length = 36)
  @NotNull
  @Size(max = 36)
  public String getCreatedBy() {
    return this.createdBy;
  }

  /** Setter for <code>public.oauth2_client_scope.created_by</code>. */
  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  /** Getter for <code>public.oauth2_client_scope.last_modified_date</code>. */
  @Column(name = "last_modified_date", precision = 6)
  public LocalDateTime getLastModifiedDate() {
    return this.lastModifiedDate;
  }

  /** Setter for <code>public.oauth2_client_scope.last_modified_date</code>. */
  public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  /** Getter for <code>public.oauth2_client_scope.last_modified_by</code>. */
  @Column(name = "last_modified_by", length = 36)
  @Size(max = 36)
  public String getLastModifiedBy() {
    return this.lastModifiedBy;
  }

  /** Setter for <code>public.oauth2_client_scope.last_modified_by</code>. */
  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }
}
