/*
 * This file is generated by jOOQ.
 */
package com.example.demo.entites;


import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/** client 設定 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(
    name = "oauth2_client_setting",
    uniqueConstraints = {
      @UniqueConstraint(
          name = "pk_oauth2_client_setting",
          columnNames = {"id"}),
      @UniqueConstraint(
          name = "uk_oauth2_client_setting",
          columnNames = {"oauth2_client_id", "property_type", "property_name"})
    })
public class Oauth2ClientSettingEntity implements Serializable {

  private static final long serialVersionUID = 1L;

  private String id;
  private String oauth2ClientId;
  private String propertyType;
  private String propertyName;
  private String propertyValue;
  private LocalDateTime createdDate;
  private String createdBy;
  private LocalDateTime lastModifiedDate;
  private String lastModifiedBy;

  public Oauth2ClientSettingEntity() {}

  public Oauth2ClientSettingEntity(Oauth2ClientSettingEntity value) {
    this.id = value.id;
    this.oauth2ClientId = value.oauth2ClientId;
    this.propertyType = value.propertyType;
    this.propertyName = value.propertyName;
    this.propertyValue = value.propertyValue;
    this.createdDate = value.createdDate;
    this.createdBy = value.createdBy;
    this.lastModifiedDate = value.lastModifiedDate;
    this.lastModifiedBy = value.lastModifiedBy;
  }

  public Oauth2ClientSettingEntity(
      String id,
      String oauth2ClientId,
      String propertyType,
      String propertyName,
      String propertyValue,
      LocalDateTime createdDate,
      String createdBy,
      LocalDateTime lastModifiedDate,
      String lastModifiedBy) {
    this.id = id;
    this.oauth2ClientId = oauth2ClientId;
    this.propertyType = propertyType;
    this.propertyName = propertyName;
    this.propertyValue = propertyValue;
    this.createdDate = createdDate;
    this.createdBy = createdBy;
    this.lastModifiedDate = lastModifiedDate;
    this.lastModifiedBy = lastModifiedBy;
  }

  /** Getter for <code>public.oauth2_client_setting.id</code>. */
  @Id
  @Column(name = "id", nullable = false, length = 10)
  @NotNull
  @Size(max = 10)
  public String getId() {
    return this.id;
  }

  /** Setter for <code>public.oauth2_client_setting.id</code>. */
  public void setId(String id) {
    this.id = id;
  }

  /** Getter for <code>public.oauth2_client_setting.oauth2_client_id</code>. OAuth Client ID */
  @Column(name = "oauth2_client_id", nullable = false, length = 10)
  @NotNull
  @Size(max = 10)
  public String getOauth2ClientId() {
    return this.oauth2ClientId;
  }

  /** Setter for <code>public.oauth2_client_setting.oauth2_client_id</code>. OAuth Client ID */
  public void setOauth2ClientId(String oauth2ClientId) {
    this.oauth2ClientId = oauth2ClientId;
  }

  /** Getter for <code>public.oauth2_client_setting.property_type</code>. 設定的類型 */
  @Column(name = "property_type", nullable = false, length = 20)
  @NotNull
  @Size(max = 20)
  public String getPropertyType() {
    return this.propertyType;
  }

  /** Setter for <code>public.oauth2_client_setting.property_type</code>. 設定的類型 */
  public void setPropertyType(String propertyType) {
    this.propertyType = propertyType;
  }

  /** Getter for <code>public.oauth2_client_setting.property_name</code>. 屬性名稱 */
  @Column(name = "property_name", nullable = false, length = 50)
  @NotNull
  @Size(max = 50)
  public String getPropertyName() {
    return this.propertyName;
  }

  /** Setter for <code>public.oauth2_client_setting.property_name</code>. 屬性名稱 */
  public void setPropertyName(String propertyName) {
    this.propertyName = propertyName;
  }

  /** Getter for <code>public.oauth2_client_setting.property_value</code>. 設定值 */
  @Column(name = "property_value", nullable = false, length = 100)
  @NotNull
  @Size(max = 100)
  public String getPropertyValue() {
    return this.propertyValue;
  }

  /** Setter for <code>public.oauth2_client_setting.property_value</code>. 設定值 */
  public void setPropertyValue(String propertyValue) {
    this.propertyValue = propertyValue;
  }

  /** Getter for <code>public.oauth2_client_setting.created_date</code>. */
  @Column(name = "created_date", nullable = false, precision = 6)
  @NotNull
  public LocalDateTime getCreatedDate() {
    return this.createdDate;
  }

  /** Setter for <code>public.oauth2_client_setting.created_date</code>. */
  public void setCreatedDate(LocalDateTime createdDate) {
    this.createdDate = createdDate;
  }

  /** Getter for <code>public.oauth2_client_setting.created_by</code>. */
  @Column(name = "created_by", nullable = false, length = 36)
  @NotNull
  @Size(max = 36)
  public String getCreatedBy() {
    return this.createdBy;
  }

  /** Setter for <code>public.oauth2_client_setting.created_by</code>. */
  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  /** Getter for <code>public.oauth2_client_setting.last_modified_date</code>. */
  @Column(name = "last_modified_date", precision = 6)
  public LocalDateTime getLastModifiedDate() {
    return this.lastModifiedDate;
  }

  /** Setter for <code>public.oauth2_client_setting.last_modified_date</code>. */
  public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  /** Getter for <code>public.oauth2_client_setting.last_modified_by</code>. */
  @Column(name = "last_modified_by", length = 36)
  @Size(max = 36)
  public String getLastModifiedBy() {
    return this.lastModifiedBy;
  }

  /** Setter for <code>public.oauth2_client_setting.last_modified_by</code>. */
  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }
}
