/*
 * This file is generated by jOOQ.
 */
package com.example.demo.entites;


import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/** oauth client 驗證方式 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(
    name = "oauth2_client_authentication_method",
    uniqueConstraints = {
      @UniqueConstraint(
          name = "pk_oauth2_client_authentication_method",
          columnNames = {"id"}),
      @UniqueConstraint(
          name = "uk_oauth2_client_authentication_method",
          columnNames = {"oauth2_client_id", "authentication_method"})
    })
public class Oauth2ClientAuthenticationMethodEntity implements Serializable {

  private static final long serialVersionUID = 1L;

  private String id;
  private String oauth2ClientId;
  private String authenticationMethod;
  private LocalDateTime createdDate;
  private String createdBy;
  private LocalDateTime lastModifiedDate;
  private String lastModifiedBy;

  public Oauth2ClientAuthenticationMethodEntity() {}

  public Oauth2ClientAuthenticationMethodEntity(Oauth2ClientAuthenticationMethodEntity value) {
    this.id = value.id;
    this.oauth2ClientId = value.oauth2ClientId;
    this.authenticationMethod = value.authenticationMethod;
    this.createdDate = value.createdDate;
    this.createdBy = value.createdBy;
    this.lastModifiedDate = value.lastModifiedDate;
    this.lastModifiedBy = value.lastModifiedBy;
  }

  public Oauth2ClientAuthenticationMethodEntity(
      String id,
      String oauth2ClientId,
      String authenticationMethod,
      LocalDateTime createdDate,
      String createdBy,
      LocalDateTime lastModifiedDate,
      String lastModifiedBy) {
    this.id = id;
    this.oauth2ClientId = oauth2ClientId;
    this.authenticationMethod = authenticationMethod;
    this.createdDate = createdDate;
    this.createdBy = createdBy;
    this.lastModifiedDate = lastModifiedDate;
    this.lastModifiedBy = lastModifiedBy;
  }

  /** Getter for <code>public.oauth2_client_authentication_method.id</code>. */
  @Id
  @Column(name = "id", nullable = false, length = 10)
  @NotNull
  @Size(max = 10)
  public String getId() {
    return this.id;
  }

  /** Setter for <code>public.oauth2_client_authentication_method.id</code>. */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * Getter for <code>public.oauth2_client_authentication_method.oauth2_client_id</code>. OAuth
   * Client ID
   */
  @Column(name = "oauth2_client_id", nullable = false, length = 10)
  @NotNull
  @Size(max = 10)
  public String getOauth2ClientId() {
    return this.oauth2ClientId;
  }

  /**
   * Setter for <code>public.oauth2_client_authentication_method.oauth2_client_id</code>. OAuth
   * Client ID
   */
  public void setOauth2ClientId(String oauth2ClientId) {
    this.oauth2ClientId = oauth2ClientId;
  }

  /**
   * Getter for <code>public.oauth2_client_authentication_method.authentication_method</code>. 驗證方式
   */
  @Column(name = "authentication_method", nullable = false, length = 20)
  @NotNull
  @Size(max = 20)
  public String getAuthenticationMethod() {
    return this.authenticationMethod;
  }

  /**
   * Setter for <code>public.oauth2_client_authentication_method.authentication_method</code>. 驗證方式
   */
  public void setAuthenticationMethod(String authenticationMethod) {
    this.authenticationMethod = authenticationMethod;
  }

  /** Getter for <code>public.oauth2_client_authentication_method.created_date</code>. */
  @Column(name = "created_date", nullable = false, precision = 6)
  @NotNull
  public LocalDateTime getCreatedDate() {
    return this.createdDate;
  }

  /** Setter for <code>public.oauth2_client_authentication_method.created_date</code>. */
  public void setCreatedDate(LocalDateTime createdDate) {
    this.createdDate = createdDate;
  }

  /** Getter for <code>public.oauth2_client_authentication_method.created_by</code>. */
  @Column(name = "created_by", nullable = false, length = 36)
  @NotNull
  @Size(max = 36)
  public String getCreatedBy() {
    return this.createdBy;
  }

  /** Setter for <code>public.oauth2_client_authentication_method.created_by</code>. */
  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  /** Getter for <code>public.oauth2_client_authentication_method.last_modified_date</code>. */
  @Column(name = "last_modified_date", precision = 6)
  public LocalDateTime getLastModifiedDate() {
    return this.lastModifiedDate;
  }

  /** Setter for <code>public.oauth2_client_authentication_method.last_modified_date</code>. */
  public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  /** Getter for <code>public.oauth2_client_authentication_method.last_modified_by</code>. */
  @Column(name = "last_modified_by", length = 36)
  @Size(max = 36)
  public String getLastModifiedBy() {
    return this.lastModifiedBy;
  }

  /** Setter for <code>public.oauth2_client_authentication_method.last_modified_by</code>. */
  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }
}
