/*
 * This file is generated by jOOQ.
 */
package com.example.demo.entites;


import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/** 存取權限資料 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(
    name = "resource_scope",
    uniqueConstraints = {
      @UniqueConstraint(
          name = "pk_resource_scope",
          columnNames = {"id"}),
      @UniqueConstraint(
          name = "uk_resource_scope_resource_scope",
          columnNames = {"resource", "scope"}),
      @UniqueConstraint(
          name = "uk_resource_scope_scope",
          columnNames = {"scope"})
    })
public class ResourceScopeEntity implements Serializable {

  private static final long serialVersionUID = 1L;

  private String id;
  private String resource;
  private String scope;
  private String description;
  private LocalDateTime createdDate;
  private String createdBy;
  private LocalDateTime lastModifiedDate;
  private String lastModifiedBy;

  public ResourceScopeEntity() {}

  public ResourceScopeEntity(ResourceScopeEntity value) {
    this.id = value.id;
    this.resource = value.resource;
    this.scope = value.scope;
    this.description = value.description;
    this.createdDate = value.createdDate;
    this.createdBy = value.createdBy;
    this.lastModifiedDate = value.lastModifiedDate;
    this.lastModifiedBy = value.lastModifiedBy;
  }

  public ResourceScopeEntity(
      String id,
      String resource,
      String scope,
      String description,
      LocalDateTime createdDate,
      String createdBy,
      LocalDateTime lastModifiedDate,
      String lastModifiedBy) {
    this.id = id;
    this.resource = resource;
    this.scope = scope;
    this.description = description;
    this.createdDate = createdDate;
    this.createdBy = createdBy;
    this.lastModifiedDate = lastModifiedDate;
    this.lastModifiedBy = lastModifiedBy;
  }

  /** Getter for <code>public.resource_scope.id</code>. */
  @Id
  @Column(name = "id", nullable = false, length = 10)
  @NotNull
  @Size(max = 10)
  public String getId() {
    return this.id;
  }

  /** Setter for <code>public.resource_scope.id</code>. */
  public void setId(String id) {
    this.id = id;
  }

  /** Getter for <code>public.resource_scope.resource</code>. 資源名稱 */
  @Column(name = "resource", nullable = false, length = 50)
  @NotNull
  @Size(max = 50)
  public String getResource() {
    return this.resource;
  }

  /** Setter for <code>public.resource_scope.resource</code>. 資源名稱 */
  public void setResource(String resource) {
    this.resource = resource;
  }

  /** Getter for <code>public.resource_scope.scope</code>. 存取權限 */
  @Column(name = "scope", nullable = false, length = 50)
  @NotNull
  @Size(max = 50)
  public String getScope() {
    return this.scope;
  }

  /** Setter for <code>public.resource_scope.scope</code>. 存取權限 */
  public void setScope(String scope) {
    this.scope = scope;
  }

  /** Getter for <code>public.resource_scope.description</code>. 描述 */
  @Column(name = "description", nullable = false, length = 50)
  @NotNull
  @Size(max = 50)
  public String getDescription() {
    return this.description;
  }

  /** Setter for <code>public.resource_scope.description</code>. 描述 */
  public void setDescription(String description) {
    this.description = description;
  }

  /** Getter for <code>public.resource_scope.created_date</code>. */
  @Column(name = "created_date", nullable = false, precision = 6)
  @NotNull
  public LocalDateTime getCreatedDate() {
    return this.createdDate;
  }

  /** Setter for <code>public.resource_scope.created_date</code>. */
  public void setCreatedDate(LocalDateTime createdDate) {
    this.createdDate = createdDate;
  }

  /** Getter for <code>public.resource_scope.created_by</code>. */
  @Column(name = "created_by", nullable = false, length = 36)
  @NotNull
  @Size(max = 36)
  public String getCreatedBy() {
    return this.createdBy;
  }

  /** Setter for <code>public.resource_scope.created_by</code>. */
  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  /** Getter for <code>public.resource_scope.last_modified_date</code>. */
  @Column(name = "last_modified_date", precision = 6)
  public LocalDateTime getLastModifiedDate() {
    return this.lastModifiedDate;
  }

  /** Setter for <code>public.resource_scope.last_modified_date</code>. */
  public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  /** Getter for <code>public.resource_scope.last_modified_by</code>. */
  @Column(name = "last_modified_by", length = 36)
  @Size(max = 36)
  public String getLastModifiedBy() {
    return this.lastModifiedBy;
  }

  /** Setter for <code>public.resource_scope.last_modified_by</code>. */
  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }
}
