/*
 * This file is generated by jOOQ.
 */
package com.example.demo.infrastructure.repositories.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.LocalDateTime;


import lombok.Data;
import lombok.extern.slf4j.Slf4j;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import jakarta.persistence.EntityListeners;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import org.springframework.data.domain.Persistable;
import jakarta.persistence.Version;

/**
 * oauth client verification method
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Slf4j
@Data
@EntityListeners({AuditingEntityListener.class})
@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler", "fieldHandler"})
@Entity
@Table(
    name = "oauth2_client_authentication_method",
    schema = "public",
    uniqueConstraints = {
        @UniqueConstraint(name = "uk_oauth2_client_authentication_method_client_method", columnNames = { "oauth2_client_id", "authentication_method" })
    }
)
public class Oauth2ClientAuthenticationMethod implements Serializable, Persistable<String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "id", nullable = false, length = 10)
    @NotNull
    @Size(max = 10)
    private String        id;

    @Column(name = "oauth2_client_id", nullable = false, length = 10)
    @NotNull
    @Size(max = 10)
    private String        oauth2ClientId;

    @Column(name = "authentication_method", nullable = false, length = 20)
    @NotNull
    @Size(max = 20)
    private String        authenticationMethod;

    @CreatedBy
    @Column(name = "created_by", length = 30)
    @Size(max = 30)
    private String        createdBy;

    @CreatedDate
    @Column(name = "created_date", nullable = false, precision = 6)
    private LocalDateTime createdDate;

    @LastModifiedBy
    @Column(name = "last_modified_by", length = 30)
    @Size(max = 30)
    private String        lastModifiedBy;

    @LastModifiedDate
    @Column(name = "last_modified_date", nullable = false, precision = 6)
    private LocalDateTime lastModifiedDate;


    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Oauth2ClientAuthenticationMethod other = (Oauth2ClientAuthenticationMethod) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.oauth2ClientId == null) {
            if (other.oauth2ClientId != null)
                return false;
        }
        else if (!this.oauth2ClientId.equals(other.oauth2ClientId))
            return false;
        if (this.authenticationMethod == null) {
            if (other.authenticationMethod != null)
                return false;
        }
        else if (!this.authenticationMethod.equals(other.authenticationMethod))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!this.lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (this.lastModifiedDate == null) {
            if (other.lastModifiedDate != null)
                return false;
        }
        else if (!this.lastModifiedDate.equals(other.lastModifiedDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.oauth2ClientId == null) ? 0 : this.oauth2ClientId.hashCode());
        result = prime * result + ((this.authenticationMethod == null) ? 0 : this.authenticationMethod.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.lastModifiedDate == null) ? 0 : this.lastModifiedDate.hashCode());
        return result;
    }
    
    @Override
    public String getId() {
        return this.id;
    }
    
    @JsonIgnore
    @Override
    public boolean isNew() {
        return null == this.createdDate;
    }
    
}
